title: Recipe
hero_image: images/banner.png
description: Create a webpage for your favourite recipe, so that your friends can make
  it!
version: 1
listed: false
copyedit: false
last_tested: "2025-09-15"
landing: true
steps:
  - title: Name your recipe
  - title: Add an ingredients section
    completion:
      - engaged
  - title: Add ingredients
  - title: Add a method section
  - title: Add steps
  - title: Add a horizontal line
  - title: Add colour
  - title: Style the line
    completion:
      - internal
  - title: Style the bullet points
    completion:
      - external
  - title: Challenges
    challenge: true
